### ISSUE TITLE
Add script to automate all Python dependencies

### ISSUE THREAD

**Issue by rjzupkoii** [bonilab/PSU-CIDD-MaSim-Support#10]
If/When there are more Python dependences to be managed for the support scripts, we should have a single script that can be run by new users that automatically installs them all.

**Comment by PakhiAgarwal** [comment]
I think we can create a requirements.txt file. The user can download all the dependencies in requirements.txt using this command.
pip install -r requirements.txt

**Comment by rjzupkoii** [comment]
@PakhiAgarwal Good idea, go ahead and create the file, add it to the repo, and update the documentation.
