### ISSUE TITLE
Study Manager attempts to run when no parameters are supplied

### ISSUE THREAD

**Issue by rjzupkoii** [bonilab/PSU-CIDD-MaSim-Support#21]
When using the study manager (formerly `addStudy.py`) the following behavior was observed:

```
user@computer$ studymanager
Configuration file not found
```

Since no parameters were supplied on the command line, the expected behavior is for the help information to be displayed in a similar manner to when the `-h` parameter is supplied:

```
user@computer$ studymanager -h
usage: studyManager.py [-h] [-a ADD] [-c CONFIGURATION] [-l]

optional arguments:
  -h, --help         show this help message and exit
  -a ADD, --add ADD
  -c CONFIGURATION
  -l, --list
```

The script should be updated to operate in this manner.

**Comment by PakhiAgarwal** [comment]
Robert, will it be considered `bug` or an `enhancement`. All the scripts are structured in this way:

    ```
if len(sys.argv) < 4:
        print("Usage-listStudy: ./addStudy -c [configuration] -l")
        print("Usage-addStudy: ./addStudy -c [configuration] -a [studyName]")
        print("configuration - the configuration file to be loaded")
        print("flag - the operation to be performed")
        print("studyName - the name of the study to be added")
        exit(0)
```

So, I structured it similarly. Earlier, if this part has not been removed then, this will be returned as output in command line

```
Usage-listStudy: ./addStudy -c [configuration] -l
Usage-addStudy: ./addStudy -c [configuration] -a [studyName]
configuration - the configuration file to be loaded
flag - the operation to be performed
studyName - the name of the study to be added
```

But I guess it is the nature of this script which makes it necessary to fix it the way you mentioned.

**Comment by rjzupkoii** [comment]
@PakhiAgarwal It would be a bug fix, since the push should be very narrowly focused on avoiding the `Configuration file not found` error message.
