### ISSUE TITLE
Add script to allow new studies to be added to a repository via the command line

### ISSUE THREAD

**Issue by rjzupkoii** [bonilab/PSU-CIDD-MaSim-Support#7]
While the LIMS offers support for adding new studies to the a projects database, a simple command line option should be available as well. The script should support the following options:

1. Create a new study (`-a '[Name]'`) in the database associated with a  project, and return the database id of the newly created study.
2. List (`-l`) all of the studies associated with a project and their ids.

An example command line may look like the following: `projectStudies [configuration] -a 'Example Study'`

Study names may be multiple words and the usual input validation and feedback to the user should be provided. Additional commands may be added in the future so the appropriate hooks should be present in the code for that to take place as well.

**Comment by PakhiAgarwal** [comment]
For command line statement, its only returning the studyname, do I need to return database id as well?
`projectStudies [configuration] -a 'Example Study'`

**Comment by rjzupkoii** [comment]
@PakhiAgarwal Adding a study to the database should return its study id.
